services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: merchant
      POSTGRES_PASSWORD: merchant
      POSTGRES_DB: merchant
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: "redis:8"
    restart: always
    ports:
      - "6379:6379"

volumes:
  db_data: